[advisories]
ignore = []

[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "Unicode-DFS-2016",
]

[bans]
multiple-versions = "deny"
highlight = "all"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [
  "https://github.com/rust-lang/crates.io-index",
]

[sources.allow-org]
github = ["artichoke"]
