---
name: Publish
"on":
  push:
    branches:
      - trunk

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    name: Build Playground
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
      CARGO_NET_GIT_FETCH_WITH_CLI: true
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set toolchain versions
        run: |
          echo "emscripten=$(cat emscripten-toolchain)" >> $GITHUB_OUTPUT
        id: toolchain_versions

      - name: Install Node.js toolchain
        uses: actions/setup-node@v4.0.1
        with:
          node-version: "lts/*"

      # Must install deps before setting up emscripten toolchain since emsdk
      # includes its own older node which does not support lockfileversion 3
      # in package-lock.json.
      - name: Install Node.js dependencies
        run: npm ci

      - name: Install Rust toolchain
        uses: artichoke/setup-rust/build-and-test@v1.11.0
        with:
          toolchain: "1.72.1"
          target: "wasm32-unknown-emscripten"

      - name: Install Ruby toolchain
        uses: ruby/setup-ruby@22fdc77bf4148f810455b226c90fb81b5cbc00a7 # v1.171.0
        with:
          ruby-version: ".ruby-version"
          bundler-cache: true

      - name: Install Emscripten toolchain
        uses: mymindstorm/setup-emsdk@6ab9eb1bda2574c4ddb79809fc9247783eaf9021 # v14
        with:
          version: ${{ steps.toolchain_versions.outputs.emscripten }}
          no-cache: true

      - name: Verify emcc version
        run: emcc -v

      - name: Compile Wasm
        run: ruby scripts/build-wasm.rb --release --verbose

      - name: Build Webapp
        run: npm run build

      # Publish step
      - name: Deploy Playground
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: artichoke.run
          user_name: artichoke-ci
          user_email: ci@artichokeruby.org
